---
  - name: ensure nginx is installed
    apt: 
      name: nginx
      state: latest
    
  - name: start nginx
    service:
      name: nginx
      state: started
  
  - name: Copy site to Nginx
    copy:
      src: "./files/index.html"
      dest: "/var/www/html/index.html"
    
    
  - name: change default
    copy:
      src: "./files/default_enabled"
      dest: "/etc/nginx/sites-enabled/default"
    notify: Restart nginx